### ISSUE TITLE
Lambda solution not viable?

### ISSUE THREAD

**Issue by markotitel** [awslabs/media-exchange-on-aws#2]
Hello, I am having a task that involves moving large quantity of large files to clients destination bucket.

While researching I've stumbled across this example repo. I am wondering why Lambda solution is not added as one of possibile tools?

Understandably 15 minutes limit is a boundary. But a lot can be  copied in that time. Adding bucket crossacount policy enables sending data to another account.

My solution is to use Stepfunctions MAP and pass a LIST of files. Lambda will do the rest with Boto3 "meta" transfer.
This example copies 25GB file in about 60 seconds.
Do you think this is okay?

```
import boto3
from boto3.s3.transfer import TransferConfig

s3 = boto3.resource('s3',config=botocore.client.Config(max_pool_connections=110))
 """Chunk size in the example is "a guess""""
transfer = TransferConfig(max_concurrency=110, multipart_chunksize=283886080)

def lambda_handler(event, context):
    key = event['file']
    bucket = event['bucket']
    store_bucket = 'cross_account_bucket_name'
    source_file = {
        'Bucket': bucket,
        'Key': key
    }
    s3.meta.client.copy(source_file, store_bucket, key),Config=transfer)
```

**Comment by provanshu** [comment]
should be good. We also have an example under tools/autoingest.
